### ISSUE TITLE
Create new wiki "There is nothing named JEE!"

### ISSUE THREAD

**Issue by BalusC** [javaee/javaee.github.io#3]
To educate starters abusing the term "JEE" I have always referred to https://java.net/projects/javaee-spec/pages/JEE.

> # There is nothing named JEE! Never use that name!
>
> ## The correct short name is "Java EE"
>
> When the enterprise Java platform was first introduced, it was called "Java 2 Platform, Enterprise Edition", with the abbreviation "J2EE". When we [revised the naming of the Java platform](http://www.oracle.com/technetwork/java/javase/overview/javanaming-2227065.html), we [didn't just drop the "2"](http://www.theserverside.com/news/thread.tss?thread_id=35561).
>
> One of the big reasons we changed the names of the platforms is because we wanted to emphasize that they're all "Java". The old names of "J2EE, "J2SE", and "J2ME" don't do that. Java is what's important to us. Java is why we're here. Java is the value we share. We need to make that clear to the world by talking about "Java EE".
>
> Please, use only the correct name "Java EE". If that's too much to say or type, call it "EE". (No, not "double-E".)

Now java.net is gone, please create a new wiki here with above content. Original page can be found here https://web.archive.org/web/20160406085843/https://java.net/projects/javaee-spec/pages/JEE

**Comment by delabassee** [comment]
See https://javaee.github.io/javaee-spec/JEE
